<a href="https://colab.research.google.com/github/Jeanette22/Proyectos-de-datos-en-Colab/blob/Google-Colab--Poryectos/PR%C3%81CTICA_DOS_Escuela_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MANEJO DE DATOS 

In [ ]:
import pandas as pd 
import numpy as np 


In [ ]:
datos = pd.read_csv (filepath_or_buffer= "/content/drive/MyDrive/saldo-turistas-serie.csv", sep= ',')
datos


indice_tiempo medio_de_transporte              pais  balanza
0          2016-01               Aérea           Bolivia   3635.9
1          2016-01               Aérea            Brasil -66768.5
2          2016-01               Aérea             Chile -11200.7
3          2016-01               Aérea          Paraguay   1996.4
4          2016-01               Aérea           Uruguay -12748.3
...            ...                 ...               ...      ...
1696       2021-03    Fluvial/Marítima           Uruguay  -4172.0
1697       2021-03    Fluvial/Marítima   EE.UU. y Canadá      6.0
1698       2021-03    Fluvial/Marítima  Resto de América      4.0
1699       2021-03    Fluvial/Marítima            Europa     15.0
1700       2021-03    Fluvial/Marítima   Resto del mundo      4.0

[1701 rows x 4 columns]

In [ ]:
datos.columns

Index(['indice_tiempo', 'medio_de_transporte', 'pais', 'balanza'], dtype='object')

#Como eliminar una columna

```
# Tiene formato de código
```



In [ ]:
# Una columna
datos1 = datos.drop(columns='medio_de_transporte')
datos1

indice_tiempo              pais  balanza
0          2016-01           Bolivia   3635.9
1          2016-01            Brasil -66768.5
2          2016-01             Chile -11200.7
3          2016-01          Paraguay   1996.4
4          2016-01           Uruguay -12748.3
...            ...               ...      ...
1696       2021-03           Uruguay  -4172.0
1697       2021-03   EE.UU. y Canadá      6.0
1698       2021-03  Resto de América      4.0
1699       2021-03            Europa     15.0
1700       2021-03   Resto del mundo      4.0

[1701 rows x 3 columns]

In [ ]:

# Eliminar dos o más columnas
datos1.drop(columns=['pais', 'balanza'])

indice_tiempo
0          2016-01
1          2016-01
2          2016-01
3          2016-01
4          2016-01
...            ...
1696       2021-03
1697       2021-03
1698       2021-03
1699       2021-03
1700       2021-03

[1701 rows x 1 columns]

# **2) ¿Cómo eliminar duplicados?**

In [ ]:
datos2=datos1[['indice_tiempo',	'balanza']]
datos2=datos1.drop_duplicates ()
datos2



indice_tiempo              pais  balanza
0          2016-01           Bolivia   3635.9
1          2016-01            Brasil -66768.5
2          2016-01             Chile -11200.7
3          2016-01          Paraguay   1996.4
4          2016-01           Uruguay -12748.3
...            ...               ...      ...
1696       2021-03           Uruguay  -4172.0
1697       2021-03   EE.UU. y Canadá      6.0
1698       2021-03  Resto de América      4.0
1699       2021-03            Europa     15.0
1700       2021-03   Resto del mundo      4.0

[1643 rows x 3 columns]

In [ ]:
datos1.shape #para ver registros y columnas 

(1701, 3)

 ¿Cómo obtener los registros duplicados?

In [ ]:
datos1[datos1.duplicated()].shape #en este caso concatenamos 

(58, 3)

**ORDENAMOS UN DATAFRAME**

In [ ]:
datos1.sort_values ('indice_tiempo') #Ordenando por el tiempo por ejemplo 

indice_tiempo              pais  balanza
0          2016-01           Bolivia   3635.9
26         2016-01   Resto del mundo   6276.2
25         2016-01            Europa  21206.0
24         2016-01  Resto de América   6600.9
23         2016-01   EE.UU. y Canadá  17933.0
...            ...               ...      ...
1675       2021-03            Brasil  -5925.0
1674       2021-03           Bolivia  -2372.3
1699       2021-03            Europa     15.0
1686       2021-03          Paraguay   -128.0
1700       2021-03   Resto del mundo      4.0

[1701 rows x 3 columns]

In [ ]:
datos1.sort_values ('indice_tiempo', ascending= False) #ASCENDENTE O DESCENTE 

indice_tiempo              pais  balanza
1700       2021-03   Resto del mundo      4.0
1687       2021-03           Uruguay   -229.0
1674       2021-03           Bolivia  -2372.3
1675       2021-03            Brasil  -5925.0
1676       2021-03             Chile  -2617.2
...            ...               ...      ...
23         2016-01   EE.UU. y Canadá  17933.0
24         2016-01  Resto de América   6600.9
25         2016-01            Europa  21206.0
26         2016-01   Resto del mundo   6276.2
0          2016-01           Bolivia   3635.9

[1701 rows x 3 columns]

# ORDENAR EN DOS COLUMNAS 

In [ ]:
from google.colab.data_table import DataTable #ORDENANDO EN DATA FRAME COLAB

# Ordenar por dos columnas
DataTable(datos1.sort_values(['indice_tiempo', 'pais']))

In [ ]:
datos3 =datos1.sort_values(['indice_tiempo', 'pais'])
DataTable (datos3)

# ¿Cómo crear una variable en un dataframe?

In [ ]:
datos3['medio_de_compra']= 'agencias_de_viajes' #LE AGREGE COLUMNA Y REGISTROS
datos3

indice_tiempo             pais   balanza     medio_de_compra
0          2016-01          Bolivia    3635.9  agencias_de_viajes
9          2016-01          Bolivia   15052.1  agencias_de_viajes
18         2016-01          Bolivia    2105.1  agencias_de_viajes
1          2016-01           Brasil  -66768.5  agencias_de_viajes
10         2016-01           Brasil -316455.3  agencias_de_viajes
...            ...              ...       ...                 ...
1691       2021-03  Resto del mundo       2.0  agencias_de_viajes
1700       2021-03  Resto del mundo       4.0  agencias_de_viajes
1678       2021-03          Uruguay    -254.0  agencias_de_viajes
1687       2021-03          Uruguay    -229.0  agencias_de_viajes
1696       2021-03          Uruguay   -4172.0  agencias_de_viajes

[1701 rows x 4 columns]

# ¿Cómo reordenar variables en un pandas data frame?

In [ ]:
# R: select()

# subset
datos4=datos3.iloc[:, 0:4]
datos4.columns

Index(['indice_tiempo', 'pais', 'balanza', 'medio_de_compra'], dtype='object')

In [ ]:
#reorden 
# reorden
datos5=datos4[['medio_de_compra', 'pais', 'balanza', 'indice_tiempo']]

In [ ]:
datos5

medio_de_compra             pais   balanza indice_tiempo
0     agencias_de_viajes          Bolivia    3635.9       2016-01
9     agencias_de_viajes          Bolivia   15052.1       2016-01
18    agencias_de_viajes          Bolivia    2105.1       2016-01
1     agencias_de_viajes           Brasil  -66768.5       2016-01
10    agencias_de_viajes           Brasil -316455.3       2016-01
...                  ...              ...       ...           ...
1691  agencias_de_viajes  Resto del mundo       2.0       2021-03
1700  agencias_de_viajes  Resto del mundo       4.0       2021-03
1678  agencias_de_viajes          Uruguay    -254.0       2021-03
1687  agencias_de_viajes          Uruguay    -229.0       2021-03
1696  agencias_de_viajes          Uruguay   -4172.0       2021-03

[1701 rows x 4 columns]

¿Cómo renombrar variables?

In [ ]:
datos5.rename(columns={'medio_de_compra':'intermediario'}).head()

intermediario     pais   balanza indice_tiempo
0   agencias_de_viajes  Bolivia    3635.9       2016-01
9   agencias_de_viajes  Bolivia   15052.1       2016-01
18  agencias_de_viajes  Bolivia    2105.1       2016-01
1   agencias_de_viajes   Brasil  -66768.5       2016-01
10  agencias_de_viajes   Brasil -316455.3       2016-01

In [ ]:
datos5.rename(str.upper, axis="columns").head() #AUMENTAR EL TAMAÑO DE LETRA

MEDIO_DE_COMPRA     PAIS   BALANZA INDICE_TIEMPO
0   agencias_de_viajes  Bolivia    3635.9       2016-01
9   agencias_de_viajes  Bolivia   15052.1       2016-01
18  agencias_de_viajes  Bolivia    2105.1       2016-01
1   agencias_de_viajes   Brasil  -66768.5       2016-01
10  agencias_de_viajes   Brasil -316455.3       2016-01

# Eliminar espacios de las columnas

In [ ]:
dato6 = datos5.rename(columns={'medio_de_compra':'medio de compra'})
dato6.head()

medio de compra     pais   balanza indice_tiempo
0   agencias_de_viajes  Bolivia    3635.9       2016-01
9   agencias_de_viajes  Bolivia   15052.1       2016-01
18  agencias_de_viajes  Bolivia    2105.1       2016-01
1   agencias_de_viajes   Brasil  -66768.5       2016-01
10  agencias_de_viajes   Brasil -316455.3       2016-01

In [ ]:
#REEMPLAZAMOS SUS ESPACIOS POR _ 
dato6.columns=dato6.columns.str.replace(' ', '_')

dato6.head()

medio_de_compra     pais   balanza indice_tiempo
0   agencias_de_viajes  Bolivia    3635.9       2016-01
9   agencias_de_viajes  Bolivia   15052.1       2016-01
18  agencias_de_viajes  Bolivia    2105.1       2016-01
1   agencias_de_viajes   Brasil  -66768.5       2016-01
10  agencias_de_viajes   Brasil -316455.3       2016-01

# 7) ¿Cómo filtrar datos con pandas query?

In [ ]:
#En R el equivalente es filter.

In [ ]:
datos5.query (" balanza > 3000 ") #filtro a mayor a 

medio_de_compra              pais  balanza indice_tiempo
0     agencias_de_viajes           Bolivia   3635.9       2016-01
9     agencias_de_viajes           Bolivia  15052.1       2016-01
19    agencias_de_viajes            Brasil   8785.9       2016-01
14    agencias_de_viajes   EE.UU. y Canadá   7487.9       2016-01
23    agencias_de_viajes   EE.UU. y Canadá  17933.0       2016-01
...                  ...               ...      ...           ...
1375  agencias_de_viajes            Europa   8838.3       2020-03
1365  agencias_de_viajes  Resto de América   8542.2       2020-03
1374  agencias_de_viajes  Resto de América   3219.8       2020-03
1367  agencias_de_viajes   Resto del mundo   4969.2       2020-03
1627  agencias_de_viajes            Europa   4211.0       2021-01

[470 rows x 4 columns]

In [ ]:
#AND #FILTRAMOS CON AND Y OR usanr QUERY 
datos5.query ("balanza > 3000 and  pais == 'Europa' ")

medio_de_compra    pais  balanza indice_tiempo
7     agencias_de_viajes  Europa  44002.4       2016-01
16    agencias_de_viajes  Europa  36038.5       2016-01
25    agencias_de_viajes  Europa  21206.0       2016-01
34    agencias_de_viajes  Europa  13002.9       2016-02
43    agencias_de_viajes  Europa  33437.9       2016-02
...                  ...     ...      ...           ...
1348  agencias_de_viajes  Europa  27473.2       2020-02
1357  agencias_de_viajes  Europa   3433.3       2020-03
1366  agencias_de_viajes  Europa  16618.8       2020-03
1375  agencias_de_viajes  Europa   8838.3       2020-03
1627  agencias_de_viajes  Europa   4211.0       2021-01

[121 rows x 4 columns]

In [ ]:
datos5.query ("balanza > 3000 or pais == 'Bolivia' ")

medio_de_compra             pais  balanza indice_tiempo
0     agencias_de_viajes          Bolivia   3635.9       2016-01
9     agencias_de_viajes          Bolivia  15052.1       2016-01
18    agencias_de_viajes          Bolivia   2105.1       2016-01
19    agencias_de_viajes           Brasil   8785.9       2016-01
14    agencias_de_viajes  EE.UU. y Canadá   7487.9       2016-01
...                  ...              ...      ...           ...
1656  agencias_de_viajes          Bolivia   -103.0       2021-02
1665  agencias_de_viajes          Bolivia      1.0       2021-02
1674  agencias_de_viajes          Bolivia  -2372.3       2021-03
1683  agencias_de_viajes          Bolivia   -150.0       2021-03
1692  agencias_de_viajes          Bolivia      1.0       2021-03

[627 rows x 4 columns]

In [ ]:
!pip install funpymodeling

     |████████████████████████████████| 215 kB 3.7 MB/s 
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2


In [ ]:
from funpymodeling.exploratory import status, freq_tbl, profiling_num

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
# Análisis univariado var numérica
profiling_num(datos5)

variable         mean       std_dev  ...  p_0.75   p_0.95   p_0.99
0  balanza -9431.563198  36242.585832  ...  3484.2  17482.5  34811.5

[1 rows x 11 columns]

In [ ]:
# Análisis univariado var categórica
freq_tbl(datos5)

      medio_de_compra  frequency  percentage  cumulative_perc
0  agencias_de_viajes       1701         1.0              1.0

----------------------------------------------------------------

               pais  frequency  percentage  cumulative_perc
0   Resto del mundo        189    0.111111         0.111111
1            Brasil        189    0.111111         0.222222
2            Europa        189    0.111111         0.333333
3  Resto de América        189    0.111111         0.444444
4             Chile        189    0.111111         0.555556
5          Paraguay        189    0.111111         0.666667
6           Uruguay        189    0.111111         0.777778
7           Bolivia        189    0.111111         0.888889
8   EE.UU. y Canadá        189    0.111111         1.000000

----------------------------------------------------------------

   indice_tiempo  frequency  percentage  cumulative_perc
0        2017-04         27    0.015873         0.015873
1        2020-06         27 

In [ ]:
datos5.max()

medio_de_compra    agencias_de_viajes
pais                          Uruguay
balanza                       51678.3
indice_tiempo                 2021-03
dtype: object

In [ ]:
datos5.min()

medio_de_compra    agencias_de_viajes
pais                          Bolivia
balanza                       -379517
indice_tiempo                 2016-01
dtype: object

In [ ]:
print ("hola mundo")

hola mundo


In [ ]:
!pip install pandas-profiling==2.7.1

     |████████████████████████████████| 252 kB 5.1 MB/s 
     |████████████████████████████████| 58 kB 5.3 MB/s 
     |████████████████████████████████| 675 kB 39.7 MB/s 
     |████████████████████████████████| 4.7 MB 26.0 MB/s 
     |████████████████████████████████| 812 kB 44.8 MB/s 
     |████████████████████████████████| 38.1 MB 1.3 MB/s 
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=313e4c9925b36947bcc373632b5d7bee8e618fb68752ca971610f1331ad40e84
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b14d250ba868768823940c3229e9950d201a26d0bd3ee8655
  Created wheel for imagehash: filename=ImageHash-4.2.1-py2.py3-none-any.whl size=295207 sha256=b6093976ebea8c97516a4bbda74b1bbc9585f25988210f6f3e3987679dcb3f21
  Stored in directory: /root/.cache/pip/wheels/4c/d5/59/5e3e297533ddb09407769762985d134135064c6831e29a914e
Successfully built htmlmin imagehash
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstallin

In [ ]:
from pandas_profiling import ProfileReport

ProfileReport(datos5)

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# ¿Cómo exportar un pandas dataframe a csv?

In [ ]:
datos5.head()

medio_de_compra     pais   balanza indice_tiempo
0   agencias_de_viajes  Bolivia    3635.9       2016-01
9   agencias_de_viajes  Bolivia   15052.1       2016-01
18  agencias_de_viajes  Bolivia    2105.1       2016-01
1   agencias_de_viajes   Brasil  -66768.5       2016-01
10  agencias_de_viajes   Brasil -316455.3       2016-01

In [ ]:
datos5.to_csv ('datos_5.csv', sep=',', index=False)


In [ ]:
import os #VEMOS CARPETA DONDE ESTA
os.getcwd()

'/content'

COMO CAMBIAMOS DIRECTORIO DE TRABAJO

In [ ]:
os.chdir('/content/drive')

datos5.to_csv('d_5.csv,  sep=',', index=False)

SyntaxError: ignored

## MODULO 3 ESTRUCTURAS DE CONTROL : se denominan PRUEBAS DE ESCRITORIOS 

USAMOS EL IF

In [ ]:
nro_de_cliente=999

if nro_de_cliente==999:
  print('es el cliente 999!!')
else:
  print('cliente no encontrado :(')

es el cliente 999!!


COMO SE ANIDAMOS 

In [ ]:
# if anidado; HACER OTRA COMPARACION, ejemplo con 999 y 111 
if nro_de_cliente==999:
  print('es el cliente 999!!')
elif nro_de_cliente==111:
  print('es el cliente 111!!')
else:
  print('cliente no encontrado :(')

es el cliente 999!!


USO DEL WHILE 

In [ ]:
# imprimir 3 elementos
i=0
while(i<3):
  i=i+1
  print(i)

1
2
3


In [ ]:
# bucle infinito: no hay condicion de salida 
while(1):
  x1=input('¿Nombre? ')

  if x1=='me aburri': #Le agrega esto para frenar el bucle 
    break
  
  print('Bienvenido! ' + x1)

¿Nombre? me aburri


# Para que usar while, si hay for! muy usados 

In [ ]:
lista=[1,2,3,4]

In [ ]:
for i in lista: #recorrer i en nuestra lista imprimir i, 
  
  if i == 3:
    break
  
  print(i)

1
2


In [ ]:

import pandas as pd

d_star_wars=pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/pablo14/datasets/main/star_wars/starwars.csv", sep=',')
d_star_wars.head()


name  height   mass  ...     gender homeworld species
0  Luke Skywalker   172.0   77.0  ...  masculine  Tatooine   Human
1           C-3PO   167.0   75.0  ...  masculine  Tatooine   Droid
2           R2-D2    96.0   32.0  ...  masculine     Naboo   Droid
3     Darth Vader   202.0  136.0  ...  masculine  Tatooine   Human
4     Leia Organa   150.0   49.0  ...   feminine  Alderaan   Human

[5 rows x 11 columns]

In [ ]:
# no hacer asi
for row in d_star_wars:
  print(row)
  


In [ ]:
# Usar iterrows() label es posicion, 
for label, row in d_star_wars[:5].iterrows():
  print ("El label es: " + str(label)) #error que habia que convertir int en str
  print(row)

El label es: 0
name          Luke Skywalker
height                   172
mass                      77
hair_color             blond
skin_color              fair
eye_color               blue
birth_year                19
sex                     male
gender             masculine
homeworld           Tatooine
species                Human
Name: 0, dtype: object
El label es: 1
name              C-3PO
height              167
mass                 75
hair_color          NaN
skin_color         gold
eye_color        yellow
birth_year          112
sex                none
gender        masculine
homeworld      Tatooine
species           Droid
Name: 1, dtype: object
El label es: 2
name                R2-D2
height                 96
mass                   32
hair_color            NaN
skin_color    white, blue
eye_color             red
birth_year             33
sex                  none
gender          masculine
homeworld           Naboo
species             Droid
Name: 2, dtype: object
El label es: 3
na

# Accediendo a cada valor:

In [ ]:
for _, row in d_star_wars[:5].iterrows(): #cuando for_ para no usar label, :5 los 5 primeros reg
  print('Personaje: ' + row['name'] + ' lugar ' + row['homeworld'])

Personaje: Luke Skywalker lugar Tatooine
Personaje: C-3PO lugar Tatooine
Personaje: R2-D2 lugar Naboo
Personaje: Darth Vader lugar Tatooine
Personaje: Leia Organa lugar Alderaan


# 4) ¿Cómo crear funciones en Python?

In [ ]:
def mi_funcion():
  print('hola mundo')

In [ ]:
mi_funcion ()

¿Cómo crear una función con parámetros?

In [ ]:
def sumar(x1, x2):
  return x1+x2

In [ ]:
sumar (2,4)

¿Cómo explorar el contenido de una función?

In [ ]:
pip install funpymodeling

In [ ]:
from funpymodeling.exploratory import status

In [ ]:
??status #vemos que tiene la funcion adentro, la ayuda, el contenido 
#firma de una funcion: son los parametros que recibe 

In [ ]:
status(d_star_wars)

variable  q_nan     p_nan  q_zeros  p_zeros  unique     type
0         name      0  0.000000        0      0.0      87   object
1       height      6  0.068966        0      0.0      45  float64
2         mass     28  0.321839        0      0.0      38  float64
3   hair_color      5  0.057471        0      0.0      12   object
4   skin_color      0  0.000000        0      0.0      31   object
5    eye_color      0  0.000000        0      0.0      15   object
6   birth_year     44  0.505747        0      0.0      36  float64
7          sex      4  0.045977        0      0.0       4   object
8       gender      4  0.045977        0      0.0       2   object
9    homeworld     10  0.114943        0      0.0      48   object
10     species      4  0.045977        0      0.0      37   object

In [ ]:
#calcula la cantidad de valores unicos 
d_star_wars.nunique().values

array([87, 45, 38, 12, 31, 15, 36,  4,  2, 48, 37])

In [ ]:
d_star_wars.columns

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'sex', 'gender', 'homeworld', 'species'],
      dtype='object')

In [ ]:
def status2(data):
  return pd.DataFrame({'variables': data.columns, 'valores_unicos':data.nunique().values})

In [ ]:
status2(d_star_wars)

variables  valores_unicos
0         name              87
1       height              45
2         mass              38
3   hair_color              12
4   skin_color              31
5    eye_color              15
6   birth_year              36
7          sex               4
8       gender               2
9    homeworld              48
10     species              37

In [ ]:
#USO DE NUMPY 

In [ ]:
import numpy as np #permite hacer operaciones con arrays dimensionales

In [ ]:
arr1=np.array([1,2,3,4,5]) #Libreria muy usada en deep learning # le paso una lista 

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1+arr1 #se duplica 

array([ 2,  4,  6,  8, 10])

In [ ]:
arr1.shape # ranking 1 #PARA TUPLA DE UN SOLO ELEMENTO, QUE TIENE UNA SOLA DIMENSIÓN ranking1

(5,)

¿Cómo crear un "tabla" en numpy?

In [ ]:
#Rank 2 array / 2D #dos dimensiones 

In [ ]:
arr2=np.array([[1,2,3,4,5], [9,8,7,6,5]])

arr2

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [ ]:
arr2.shape #vemos dos dimensiones y 5 registros #Con nunmpy, mas shape podemos analizar imagenes por ej: ver sus pix y colores totales. 

(2, 5)

In [ ]:
#Rank 3 array / 3D usamos ]]] dentro de una tupla 
arr3=np.array([[[1,2,3,4,5], [9,8,7,6,5]]]) 

In [ ]:
arr3.shape #un caso en la 1er d, 2 en la 2 dim, y 5 en la 3ra : 1 de todo el bombo, 2 porque hay dos listas, y 5 es cada elemento.

(1, 2, 5)

# Cómo hacer reshape en numpy?: Muy usado, le cambia el shape de los datos, sin cambiar los datos 

In [ ]:
arr3 = np.array([1,2,3,4,5,6]) #muy usado deeplearning: para procesar info en redes neuronal. 
print(arr3)           #Recordar: 1 dimnesio = a vector, 2 dimensiones = tabla, 3 dimensiones = cubo, 4 =... 
print(arr3.shape) 

[1 2 3 4 5 6]
(6,)


In [ ]:
arr4=arr3.reshape((2,3))
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr4.shape

(2, 3)

# ¿Cómo hacer flatten de un numpy array?

In [ ]:
arr5=arr4.flatten()
arr5

array([1, 2, 3, 4, 5, 6])

2.3) ¿Cómo hacer slice de numpy?

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
#1er elemento
arr1[0] #Recordar que siempre empiezan desde el 0, 1, 2, 3, 4, 5 ...

1

In [ ]:
#ver varios: de donde hasta donde
arr1[1:3]

array([2, 3])

# C.2.4) ¿Cómo acceder a arrays n-dimensionales?

In [ ]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr4[0,:] #vemos todos los registros, de la fila 0

array([1, 2, 3])

In [ ]:
arr4[1,0]

4

In [ ]:
arr4[1,0:2]

array([4, 5])

In [ ]:
# acceder a toda la 1er dimensión
arr4[0] 

array([1, 2, 3])

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="300px">

[Fuente](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html)